In [40]:
import psycopg2
import pandas as pd
conn = psycopg2.connect("host=pacs.lais.huol.ufrn.br dbname=pacsdb user=jailton password=l41sjailton")
cur = conn.cursor()

In [41]:
meses = range(1,13)
anos = range(2013,2017)
modalidades = ( "RTSTRUCT", "US", "CR", "MR", "CT",
                "XA", "SC", "PR", "OT", "PDF", "PT",
                "XC", "SR", "KO", "ECG", "DX")

estudo = {}

In [42]:
for ano in anos:
    if ano not in estudo:
        estudo[ano] = {}
        dados_ano = estudo[ano]

    for mes in meses:
        quantidades_mes = []
        for modalidade in modalidades:
            sql = """
            SELECT COUNT(*) from series
            WHERE extract(year from created_time) = %d AND extract(month from created_time) = %d
            AND modality LIKE '%s'
            """ % (ano, mes, "%"+modalidade+"%")
            cur.execute(sql)
            quantidades_mes.append(cur.fetchall()[0][0])
        dados_ano[mes] = pd.Series(quantidades_mes, index=modalidades)

In [52]:
ano2016 = pd.DataFrame(estudo[2016])
ano2016

,1,2,3,4,5,6,7,8,9,10,11,12
Mods.,,,,,,,,,,,,
RTSTRUCT,0,0,0,0,0,0,0,0,0,0,0,0
US,936,991,1214,905,881,1302,917,1353,721,740,864,598
CR,611,709,958,2521,2511,1224,1930,3517,2123,1030,2328,2085
MR,1445,1747,1231,1165,1899,1758,1725,2280,2214,1316,1404,1888
CT,2474,2749,2191,2962,3139,3686,2669,2864,3216,2677,2225,2341
XA,1561,1356,1592,1323,1004,1870,1713,2153,39,1350,1503,849
SC,0,0,0,0,0,1,0,0,7,0,0,7
PR,0,0,5,0,1,0,10,13,0,0,0,2
OT,0,0,0,0,0,0,0,0,0,843,743,263
PDF,0,0,0,0,0,0,0,0,0,0,0,0
PT,0,0,0,0,0,0,0,0,0,0,0,0
XC,1669,1549,0,0,14,0,0,0,0,0,0,0
SR,172,218,244,221,127,284,203,271,184,234,232,124
KO,0,0,0,0,0,3,0,2,0,0,0,1
ECG,0,0,0,0,0,0,0,0,0,0,0,0
DX,0,0,0,0,0,0,0,0,0,0,0,0

In [46]:
ano2015 = pd.DataFrame(estudo[2015])
ano2015

,1,2,3,4,5,6,7,8,9,10,11,12
RTSTRUCT,0,1,0,0,0,0,0,0,0,0,0,0
US,951,978,1051,1357,1278,825,1404,1367,1467,1169,1068,871
CR,0,0,0,0,0,0,294,1046,1600,2871,2292,1245
MR,1597,1630,861,19,9,1560,6795,1871,1607,1758,920,802
CT,1871,3390,2774,1834,1286,967,2794,3303,2324,2578,3045,1608
XA,1282,1270,1407,396,1159,1227,2104,2215,2222,1951,1742,1736
SC,0,1,0,0,6,0,0,0,0,0,0,0
PR,1,0,0,0,0,0,3,0,0,0,0,0
OT,0,0,0,0,0,0,0,0,0,0,0,0
PDF,0,0,0,0,2,0,0,0,0,0,0,0
PT,0,27,0,0,0,0,0,0,0,0,0,0
XC,0,0,0,0,0,0,1462,2926,2000,268,1827,41
SR,141,166,220,234,192,174,390,272,296,293,186,159
KO,0,4,0,0,2,0,36,0,0,0,0,0
ECG,0,0,0,0,2,0,0,0,0,0,0,0
DX,1123,1095,1217,0,0,6105,1526,0,0,0,11,0

In [53]:
ano2014 = pd.DataFrame(estudo[2014])
ano2014

,1,2,3,4,5,6,7,8,9,10,11,12
RTSTRUCT,0,0,0,0,0,0,0,0,0,0,0,0
US,310,510,401,517,921,593,739,1032,786,842,811,1159
CR,0,0,0,0,0,0,0,0,0,0,0,0
MR,472,574,949,484,566,800,598,663,1209,1054,1181,1388
CT,1864,2066,1440,2318,2139,1486,2126,2472,2236,2598,2717,2091
XA,709,1090,897,979,1001,776,941,1363,1105,918,1528,1213
SC,0,0,0,0,0,0,0,0,0,0,0,0
PR,0,0,0,0,0,4,0,0,0,0,0,0
OT,0,0,0,0,0,0,0,0,0,0,0,0
PDF,0,0,0,0,0,0,0,0,0,0,0,0
PT,0,0,0,0,0,0,0,0,0,0,0,0
XC,0,0,0,0,0,0,0,0,0,0,0,0
SR,0,0,0,0,172,155,186,229,161,170,164,237
KO,0,1,0,0,0,1,0,0,0,0,0,0
ECG,2,0,0,0,0,0,0,0,0,3,0,6
DX,972,4018,2242,2205,2407,1504,2186,2817,4236,3718,3630,1909

In [54]:
ano2013 = pd.DataFrame(estudo[2013])
ano2013

          1   2   3   4   5   6   7     8     9     10    11    12
RTSTRUCT   0   0   0   0   0   0   0     0     0     0     0     0
US         0   0   0   0   0   0   0    37   415   432   447   272
CR         0   0   0   0   0   0   0     0     0     0     0     0
MR         0   0   0   0   0   0   0     0     0   284   596   403
CT         0   0   0   0   0   0   0  1304  1498  2305  2304  1474
XA         0   0   0   0   0   0   0   500   968   604  1015   911
SC         0   0   0   0   0   0   0     0     0     0     0     0
PR         0   0   0   0   0   0   0     0     0     0     0     0
OT         0   0   0   0   0   0   0     0     0     0     0     0
PDF        0   0   0   0   0   0   0     0     0     0     0     0
PT         0   0   0   0   0   0   0     0     0     0     0     0
XC         0   0   0   0   0   0   0     0     0     0     0     0
SR         0   0   0   0   0   0   0     0     1     0     0     0
KO         0   0   0   0   0   0   0     0     0     0     0     0
ECG        0   0   0   0   0   0   0     0     0     2     3     0
DX         0   0   0   0   0   0   0  4088  2689  2089  2925  2542